### ISSUE TITLE
Found as a Trojan

### ISSUE THREAD

**Issue by Twear81** [LeDragoX/Win10SmartDebloat#10]
### Describe the Bug

Windows defender detect it as :
![image](https://user-images.githubusercontent.com/48881564/143776867-c1997fc0-e722-466a-a1a1-cd4a520ebe7a.png)

### How can this issue be reproduced?

Download it

### Operating System

Windows 11 (64bit)

### Operating System Version

21H2 build 22000.348

### Date Executed

28/11/2021

**Comment by LeDragoX** [comment]
hmmm, lol, that was unexpected.

**Comment by LeDragoX** [comment]
To specify better which files are related to the `Win10ScriptGUI.ps1`, i'll list them, by now:
### At the Start
- `\src\lib\install-package.psm1`
- `\src\lib\gui-helper.psm1`
- `\src\lib\set-script-policy.psm1`
- `\src\lib\simple-message-box.psm1`
- `\src\lib\title-templates.psm1`
- `\src\assets\windows-11-logo.png`
- `\src\assets\script-logo.png`
- 

### For Apply Tweaks button:
- `\src\scripts\backup-system.ps1`
- `\src\scripts\silent-debloat-softwares.ps1`
- `\src\scripts\optimize-scheduled-tasks.ps1`
- `\src\scripts\optimize-services.ps1`
- `\src\scripts\remove-bloatware-apps.ps1`
- `\src\scripts\optimize-privacy-and-performance.ps1`
- `\src\scripts\personal-tweaks.ps1`
- `\src\scripts\optimize-security.ps1`
- `\src\scripts\optimize-optional-features.ps1`
- `\src\scripts\remove-onedrive.ps1`
- `\src\assets\script-logo2.png`

### For Repair Windows button:
- `\src\scripts\backup-system.ps1`
- `\src\scripts\repair-windows.ps1`

### For Install OneDrive Button:
- `\src\utils\install-onedrive.ps1`

### For Reinstall Pre-Installed Apps button:
- `\src\utils\reinstall-pre-installed-apps.ps1`

### For Revert Tweaks button:
- `\src\scripts\optimize-scheduled-tasks.ps1`
- `\src\scripts\optimize-services.ps1`
- `\src\scripts\optimize-privacy-and-performance.ps1`
- `\src\scripts\personal-tweaks.ps1`
- `\src\scripts\optimize-optional-features.ps1`

Editing into table...

**Comment by LeDragoX** [comment]
Hope this worked @Twear81, could you test again and tell me? Or someone using Defender on Win 11?
Because on my PC it didn't find as a virus anymore, but Virus Total After removing the Activator **found**.

![image](https://user-images.githubusercontent.com/27643047/144068691-b22cea74-44c0-41df-ab46-fe53f0f910c2.png)

This is a false positive, but i really didn't find where this behaviors like a Trojan...

**Comment by Twear81** [comment]
I can confirm now it's no longer detected as a Trojan by Windows Security on Windows 11 ! Last commit on 30 Nov ;)

**Comment by LeDragoX** [comment]
### Fixed the "Trojan behaviour" detected only by DrWeb antivirus...

![image](https://user-images.githubusercontent.com/27643047/144091322-c52e08c4-8976-4ca3-8fcf-01af58a1c77d.png)
