### ISSUE TITLE
Acquire Store versions of WSL2 instead

### ISSUE THREAD

**Issue by sr229** [LeDragoX/Win10SmartDebloat#12]
### Description

Right now we're using the legacy feature version which isn't going to be updated as much. The Store version is updated more frequently and independent of the system so you'll want that installed instead.

### Reason

The [Blog post](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) explains why we'd want the preview version more.

### Examples

N/A

**Comment by LeDragoX** [comment]
<div align="center">

![image](https://user-images.githubusercontent.com/27643047/145819971-295172de-98ac-4d75-af7e-5fe212e15b92.png)
**Oops**
</div>

- Much easier to install, when i got some time after the last college homeworks, i'll do this
- Only `Windows 11` can install from there, but it's great to see that.

Thanks for the tip!

**Comment by LeDragoX** [comment]
@sr229 can you check if this is what you suggested?

**Comment by LeDragoX** [comment]
If the installation succeeds, it remove the `legacy WSL` from `optional features`

**Comment by sr229** [comment]
> @sr229 can you check if this is what you suggested?

Yep, verified the product ID and everything, this is correct.
