### ISSUE TITLE
Add VCRedist installation option

### ISSUE THREAD

**Issue by GleitonCampos** [LeDragoX/Win10SmartDebloat#15]
### Description

Just a small addition:
Add a button in GUI version to install the choco "VCRedist All" package (https://community.chocolatey.org/packages/vcredist-all)

### Reason

Improve the script adding some common software.

### Examples

N/A

**Comment by LeDragoX** [comment]
This feature already exists, but it uses `Winget` (which is better), as it is the official package manager to all the programs.
On the GUI its the _"Install Gaming Dependencies"_ button.

**Source:** https://github.com/LeDragoX/Win10SmartDebloat/blob/main/src/scripts/install-gaming-dependencies.ps1#L26
![image](https://user-images.githubusercontent.com/27643047/154365645-a5133030-a7a1-44bd-aa5a-bd7a262d4878.png)

**Comment by GleitonCampos** [comment]
Oh, sorry for miss this feature! Thank you very much.
